version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        USERID: ${USERID:-1000}
    environment:
      MONGODB_URL: mongodb://mongo:27017
      MONGODB_DB: mongo
      MONGODB_USER: root
      MONGODB_PASSWORD: root
    volumes:
      - ./app:/var/www/html
    networks:
      - default

  nginx:
    image: nginx:1.23.2
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - default

networks:
  default:
    driver: bridge
